version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: gradle
    directory: gradle
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
