version: "1.0"
linter: jetbrains/qodana-jvm:latest
projectJDK: 11
profile:
  name: qodana.recommended.full
exclude:
  - name: All
    paths:
      - node_modules/
      - common/node_modules/
      - scan/node_modules/
      - vsts/node_modules/
      - scan/jest.config.js
      - common/lib
      - scan/lib
      - scan/dist
      - scan/__tests__
      - vsts/lib
      - vsts/QodanaScan
      - build.gradle.kts
      - settings.gradle.kts
include:
  - name: Eslint
  - name: GrazieInspection
  - name: IdentifierGrammar
  - name: LanguageDetectionInspection
  - name: CheckDependencyLicenses
licenseRules:
  - keys:
      - "Apache-2.0"
    allowed:
      - "0BSD"
      - "FPL"
      - "BlueOak-1.0.0"
dependencyOverrides:
  - name: "buffers"
    version: "0.1.1"
    licenses:
      - key: "MIT"
        url: "https://github.com/mk-pmb/binary-pmb-node/blob/master/LICENSE.MIT.txt"
