name: 'Qodana - Linters'
description: 'Qodana is a code quality monitoring tool that identifies bugs, duplications, and imperfections.'
author: 'JetBrains'

inputs:
  linter:
    description: 'Qodana linter. All possible values can be found here: https://hub.docker.com/r/jetbrains/qodana'
    required: true
    default: "jetbrains/qodana-jvm-community"
  project-dir:
    description: 'Root directory of the project to be analyzed'
    required: false
    default: "${{ github.workspace }}"
  results-dir:
    description: 'Directory to store the analysis results'
    required: false
    default: "${{ runner.temp }}/qodana/results"
  cache-dir:
    description: 'Directory to store Qodana caches'
    required: false
    default: "${{ runner.temp }}/qodana-caches"
  idea-config-dir:
    description: 'IntelliJ IDEA configuration directory'
    required: false
  gradle-settings-path:
    description: 'Provide path to gradle.properties file. An example: "/your/custom/path/gradle.properties"'
    required: false
  additional-volumes:
    description: 'Mount additional volumes to Docker container'
    required: false
  additional-env-variables:
    description: 'Pass additional environment variables to docker container'
    required: false
  inspected-dir:
    description: 'Directory to be inspected. If not specified, the whole project is inspected by default'
    required: false
  baseline-path:
    description: 'Run in baseline mode. Provide the path to an exisitng SARIF report to be used in the baseline state calculation'
    required: false
  baseline-include-absent:
    description: 'Include in the output report the results from the baseline docker that are absent in the current docker'
    required: false
    default: "false"
  changes:
    description: 'Inspect uncommitted changes and report new problems'
    required: false
    default: "false"
  script:
    description: 'Override the default docker scenario'
    required: false
  fail-threshold:
    description: 'Set the number of problems that will serve as a quality gate. If this number is reached, the inspection docker is terminated'
    required: false
  profile-name:
    description: 'Name of a profile defined in project'
    required: false
  profile-path:
    description: 'Absolute path to the profile file'
    required: false
  upload-result:
    description: 'Upload Qodana results as an artifact to the job'
    required: false
    default: "true"
  use-caches:
    description: 'Utilize GitHub caches for Qodana runs'
    required: false
    default: "true"
  use-annotations:
    description: 'Use annotations to mark the results in GitHub user interface'
    required: false
    default: "true"
  github-token:
    description: 'GitHub token to be used for uploading annotations'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
