name: 'Qodana Scan'
description: 'Scan your projects with Qodana on GitHub. Docs: https://jb.gg/qodana-github-action'
author: 'JetBrains'
branding:
  color: "black"
  icon: "bar-chart-2"
inputs:
  args:
    description: 'Additional Qodana CLI arguments. Separate multiple arguments with commas (`,`).'
    required: false
    default: ""
  results-dir:
    description: 'Directory to store the analysis results'
    required: false
    default: "${{ runner.temp }}/qodana/results"
  cache-dir:
    description: 'Directory to store Qodana caches'
    required: false
    default: "${{ runner.temp }}/qodana/caches"
  use-caches:
    description: 'Automatically restore and save Qodana caches using GitHub caches'
    required: false
    default: "true"
  additional-cache-hash:
    description: 'Pass additional cache hash extension'
    required: false
    default: "${{ github.sha }}"
  upload-result:
    description: 'Upload Qodana results on GitHub as an artifact to the job'
    required: false
    default: "true"
  artifact-name:
    description: 'Specify Qodana results artifact name, used for results uploading'
    required: false
    default: "qodana-report"
  use-annotations:
    description: 'Use annotations to mark the results in the GitHub user interface'
    required: false
    default: "true"
  github-token:
    description: 'GitHub token to be used for uploading annotations'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'scan/dist/index.js'
