name: 'Qodana - Code Inspection'
description: 'Qodana is a code quality monitoring tool that identifies bugs, duplications, and imperfections.'
author: 'JetBrains'

inputs:
  project-dir:
    description: 'Project folder to inspect'
    required: false
    default: "${{ github.workspace }}"
  results-dir:
    description: 'Save results to folder'
    required: false
    default: "${{ github.workspace }}/qodana"
  cache-dir:
    description: 'Save cache to folder'
    required: false
    default: "/home/runner/work/qodana-cache"
runs:
  using: 'composite'
  steps:
    - run: docker run -v ${{inputs.project-dir}}:/data/project -v ${{inputs.results-dir}}:/data/results -v  ${{inputs.cache-dir}}:/data/cache jetbrains/qodana:2021.1-eap --save-report
      shell: bash
    - run: sudo find ${{inputs.cache-dir}} -type d -exec chmod 755 {} + ; sudo find ${{inputs.cache-dir}} -type f -exec chmod 544 {} +
      shell: bash