name: 'Qodana - Code Inspection'
description: 'Qodana is a code quality monitoring tool that identifies bugs, duplications, and imperfections.'
author: 'JetBrains'

inputs:
  project-dir:
    description: 'Project folder to inspect'
    required: false
    default: '/github/workspace'
  results-dir:
    description: 'Save results to folder'
    required: false
    default: '/github/workspace/qodana'
  report-dir:
    description: 'Save html report to folder'
    required: false
    default: '/github/workspace/report'
  cache-dir:
    description: 'Save cache to folder'
    required: false
    default: '/github/home/qodana-cache'
runs:
  using: 'docker'
  image: 'docker://jetbrains/qodana:2021.1-eap'
  args:
    - --project-dir=${{inputs.project-dir}}
    - --results-dir=${{inputs.results-dir}}
    - --report-dir=${{inputs.report-dir}}
    - --cache-dir=${{inputs.cache-dir}}
    - --save-report