# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default 

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

  - task: QodanaScan@2024
    env:
      AGENT_USE_NODE10: true
    inputs:
      uploadResult: true
      useNightly: true
      args: --log-level,debug,--ide,QDJVMC-EAP,--property,idea.headless.enable.statistics=false,--config,.github/qodana.yaml

