/*
 * Copyright 2021-2024 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.qodana

// CHECKSUMS is a map of Qodana CLI versions binaries and their checksums.
// Note: the content of this file is generated by the build script. Do not modify it manually.
val CHECKSUMS = mapOf(
    "2023.3.2" to mapOf(
        "windows_x86_64" to "da666d34e60167461ed75ce69a8d0dced33255d7d0785c4a3cdc33419cada022",
        "windows_arm64" to "4c7d2363bf0ffe1f7269dde4af03bb3b8586f8e213f1cb3bc3c77d1d9f4a0e90",
        "linux_x86_64" to "71abcb82489daba6200b5791ee56058a2f8ad8a87f8bbdcd33e6180906e1e482",
        "linux_arm64" to "47f86194e30a33a702971cbc33c78a38aa2e1af18eeccabe6d10a7a36451d43a",
        "darwin_x86_64" to "72b85e7e5a28f49b553df9e8efcb789c2622c41694f06ad9f83833baf335c8c5",
        "darwin_arm64" to "468178072a0ffbdb80d8305a88ef7b671d484205c20c043adc7c257ddc0032a4"
    ),
    "2024.1.6" to mapOf(
        "windows_x86_64" to "cba8236cc8c650ecac61d543e744cb20e4763a26a075f37dc5909880de93b1f3",
        "windows_arm64" to "b0547cd008959ca275d0a945e9ae025c4c9271cffa0e87ffaac883d164bf84e2",
        "linux_x86_64" to "597d870f4c747d04d0280956306e2e7b9e003662d4600d93c1b69fcaffc2bb7b",
        "linux_arm64" to "b127fc5fe46f5c197781ff0f30de4e4f68b3ba19c5748dcb87c3d1417a3d9f89",
        "darwin_x86_64" to "847495bdeb8bffd2e13b0af8decdbd3b7b23735ad18746d0629e7a5e25c867de",
        "darwin_arm64" to "e87ff91a64b8c77466938ee2020bf8636b46016ff9b587aa3fcaa356d6de6b72"
    ),
    "2024.1.7" to mapOf(
        "windows_x86_64" to "f0eedf835527f192d8e22b67ecfcd34c719059795e5f4556a4fb794f8df7db3e",
        "windows_arm64" to "e9b51ceaf547b407a89ce2e1de1772d1457aca1574ba5680166eb65d20c7713b",
        "linux_x86_64" to "b98b54405c54203976b3b28e18a57b4f33bdb6f2bb7c5768ef3560cb4dc5cfcb",
        "linux_arm64" to "cfd842980e4c237cf54fcdff9e68f3a568e77f275e4e2a25e79d95c2a2ef62f5",
        "darwin_x86_64" to "21ce44b0ab96573ef75406e741e132e2f8c92c2e24d1d0370871276135c525ca",
        "darwin_arm64" to "fee1093b5d8202405615f2630ae44621c3168e59b7f5703a9e453f8666a0cae2"
    ),
    "2024.1.8" to mapOf(
        "windows_x86_64" to "4bef4954573b37a45ed2eaaf6688a30f1a006bc8470f2189ebece44816a3d88d",
        "windows_arm64" to "f97611e8a40a61ee44f914a20ccd2880f05a38321d450044e33ce1aeffcaaf8c",
        "linux_x86_64" to "e5d3302e5c00d6bdc0f530f4e4852805b88abc65f34943bc42a61bd33e0bd5c5",
        "linux_arm64" to "f1b8ba1be5dc453ba87de4f75c5f86e59445bb13de407f809ce4475a04b1a70d",
        "darwin_x86_64" to "8fcbeba68026f33a0d265b064bbb607e86c8775d4e9aade0cabf1b2620ad6015",
        "darwin_arm64" to "b80167f5a4ff2c054671b985ab1dcc4d59d149c86fd1155935543ad4d05c7aa7"
    ),
    "2024.1.9" to mapOf(
        "windows_x86_64" to "dd893bced4613b99a317459b0c912ff5e5d72d56fd39acf9d7be7c62776d9024",
        "windows_arm64" to "87b6c3419f50097ccf0a126206a632f1a2a58255c7119296d0ee84b6ac14864e",
        "linux_x86_64" to "9859b14a67b384015f6e65cb6c8835ba750e56ee8421f3ee14c6b2b3f8f9d8a3",
        "linux_arm64" to "67f7845b390ba0de022ac60beea84a3eb2d69524806b03a7928f0953c10eebd7",
        "darwin_x86_64" to "226ffc4887ebab497a44f7c72f68589104fe5c34141b874eab280a89a5a4c74d",
        "darwin_arm64" to "89fd2f7752478ed0a61961cdc839a6317d5336ebbacf2adf9f9abdb2d5b6a92d"
    ),
)