/*
 * Copyright 2021-2024 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.qodana

// CHECKSUMS is a map of Qodana CLI versions binaries and their checksums.
// Note: the content of this file is generated by the build script. Do not modify it manually.
val CHECKSUMS = mapOf(
    "2023.3.2" to mapOf(
        "windows_x86_64" to "da666d34e60167461ed75ce69a8d0dced33255d7d0785c4a3cdc33419cada022",
        "windows_arm64" to "4c7d2363bf0ffe1f7269dde4af03bb3b8586f8e213f1cb3bc3c77d1d9f4a0e90",
        "linux_x86_64" to "71abcb82489daba6200b5791ee56058a2f8ad8a87f8bbdcd33e6180906e1e482",
        "linux_arm64" to "47f86194e30a33a702971cbc33c78a38aa2e1af18eeccabe6d10a7a36451d43a",
        "darwin_x86_64" to "72b85e7e5a28f49b553df9e8efcb789c2622c41694f06ad9f83833baf335c8c5",
        "darwin_arm64" to "468178072a0ffbdb80d8305a88ef7b671d484205c20c043adc7c257ddc0032a4"
    ),
    "2024.1.6" to mapOf(
        "windows_x86_64" to "cba8236cc8c650ecac61d543e744cb20e4763a26a075f37dc5909880de93b1f3",
        "windows_arm64" to "b0547cd008959ca275d0a945e9ae025c4c9271cffa0e87ffaac883d164bf84e2",
        "linux_x86_64" to "597d870f4c747d04d0280956306e2e7b9e003662d4600d93c1b69fcaffc2bb7b",
        "linux_arm64" to "b127fc5fe46f5c197781ff0f30de4e4f68b3ba19c5748dcb87c3d1417a3d9f89",
        "darwin_x86_64" to "847495bdeb8bffd2e13b0af8decdbd3b7b23735ad18746d0629e7a5e25c867de",
        "darwin_arm64" to "e87ff91a64b8c77466938ee2020bf8636b46016ff9b587aa3fcaa356d6de6b72"
    ),
    "2024.1.7" to mapOf(
        "windows_x86_64" to "f0eedf835527f192d8e22b67ecfcd34c719059795e5f4556a4fb794f8df7db3e",
        "windows_arm64" to "e9b51ceaf547b407a89ce2e1de1772d1457aca1574ba5680166eb65d20c7713b",
        "linux_x86_64" to "b98b54405c54203976b3b28e18a57b4f33bdb6f2bb7c5768ef3560cb4dc5cfcb",
        "linux_arm64" to "cfd842980e4c237cf54fcdff9e68f3a568e77f275e4e2a25e79d95c2a2ef62f5",
        "darwin_x86_64" to "21ce44b0ab96573ef75406e741e132e2f8c92c2e24d1d0370871276135c525ca",
        "darwin_arm64" to "fee1093b5d8202405615f2630ae44621c3168e59b7f5703a9e453f8666a0cae2"
    ),
    "2024.1.8" to mapOf(
        "windows_x86_64" to "4bef4954573b37a45ed2eaaf6688a30f1a006bc8470f2189ebece44816a3d88d",
        "windows_arm64" to "f97611e8a40a61ee44f914a20ccd2880f05a38321d450044e33ce1aeffcaaf8c",
        "linux_x86_64" to "e5d3302e5c00d6bdc0f530f4e4852805b88abc65f34943bc42a61bd33e0bd5c5",
        "linux_arm64" to "f1b8ba1be5dc453ba87de4f75c5f86e59445bb13de407f809ce4475a04b1a70d",
        "darwin_x86_64" to "8fcbeba68026f33a0d265b064bbb607e86c8775d4e9aade0cabf1b2620ad6015",
        "darwin_arm64" to "b80167f5a4ff2c054671b985ab1dcc4d59d149c86fd1155935543ad4d05c7aa7"
    ),
    "2024.1.9" to mapOf(
        "windows_x86_64" to "dd893bced4613b99a317459b0c912ff5e5d72d56fd39acf9d7be7c62776d9024",
        "windows_arm64" to "87b6c3419f50097ccf0a126206a632f1a2a58255c7119296d0ee84b6ac14864e",
        "linux_x86_64" to "9859b14a67b384015f6e65cb6c8835ba750e56ee8421f3ee14c6b2b3f8f9d8a3",
        "linux_arm64" to "67f7845b390ba0de022ac60beea84a3eb2d69524806b03a7928f0953c10eebd7",
        "darwin_x86_64" to "226ffc4887ebab497a44f7c72f68589104fe5c34141b874eab280a89a5a4c74d",
        "darwin_arm64" to "89fd2f7752478ed0a61961cdc839a6317d5336ebbacf2adf9f9abdb2d5b6a92d"
    ),
    "2024.1.11" to mapOf(
        "windows_x86_64" to "b652d9d5448aaa63ce82692831b50c2187d4e0675f934d5880e02ceb6e8980c9",
        "windows_arm64" to "25eb03c3226b80e3a6f3e68c5190c61e3c04f8c65f249b26547585e97171db92",
        "linux_x86_64" to "13a4936eff5fc862171211338768972043979f48923524d4b8eb7314d76fc4f4",
        "linux_arm64" to "338372c285cfd35409769393c357e1af190823317e4ec9d4a04acd37ecfadcda",
        "darwin_x86_64" to "74f6f25176fde39018a2ee627ebbbf3a1fb9c6e5b9db911996929ab8d1dd126a",
        "darwin_arm64" to "68fff81b14a9725ffcc156f947dd23e8147203c06c952366005021c69ba40a57"
    ),
    "2024.2.2" to mapOf(
        "windows_x86_64" to "eff2707f64ce0825e1164ad4b9b6fb604e47f7fb0a6920e7939661b1c8623eaf",
        "windows_arm64" to "8849ad5eb4b05553a32199fea8649c55412e2a00655274c7de6728a51064175b",
        "linux_x86_64" to "0ab1e76c116f3f9bf9465dc2d284eb8c2cbddcf957dcf413d91b3139ca260919",
        "linux_arm64" to "7fce163bd13a0e3f7fe6d8e61f964d1b3143000ac6bb5af76957ccc896012114",
        "darwin_x86_64" to "5f110c687367ba3bb47609f5bb64e2216f18bfb8cf44c1c8272846e844932d8b",
        "darwin_arm64" to "dc2b444375f8ac15f6a1f5fa33984d199b1c497446798f221a76481f16cae32c"
    ),
    "2024.2.3" to mapOf(
        "windows_x86_64" to "5d865b0f13d5cd5c5b2ae0d949a591806ade6e7f4580727bce4a415108eafe95",
        "windows_arm64" to "e0f61cc37ad37d549605ab6a7d5dd279df08554c9610e04c828662a6955c5059",
        "linux_x86_64" to "b8b70cdd8be9f79037dd511cbdbde70737834c46f35faa3a14acaca41f292748",
        "linux_arm64" to "293ea36dbb53f47e4585468d80a788af12c9e0e1290bf0af69cddb8a3c165602",
        "darwin_x86_64" to "1dafe45b1b1fdfe5b08b2896713befa19d46c5df3b7b138b6a1363fac09d34cf",
        "darwin_arm64" to "d41a0251eb27bf97ab494d15fc7b4b952113bb303ba0c830cd2a6fcbd58cb8c3"
    ),
    "2024.2.5" to mapOf(
        "windows_x86_64" to "91fae0fb56b74f1ea5e032a0a702c884ae8de21d1c7e9c937c1f354758c72289",
        "windows_arm64" to "cd1cc066f6be3e15c6c764b9217df11b2dab2e538d2f16784f5ec333b912be41",
        "linux_x86_64" to "55e1d21480f7158c1685404c0876b092ca007d7e13c55599d6e26d4bd99f2463",
        "linux_arm64" to "0ce0ffc17cd01ab91f5ce0404bfd82c79051829742cba20f69350f41da812fef",
        "darwin_x86_64" to "406dadbd2617665ceb6ae1c5241ddcfaab4b7f4d1f3ae16cd3d1b9f788cf072b",
        "darwin_arm64" to "3618a5a65e08ece566f461afe2ed98223a5b3a5fceb2561e58fddcc8aa718f2e"
    ),
    "2024.2.6" to mapOf(
        "windows_x86_64" to "190cbbf7334dc13556b3926d347947ee7170174e385c48e79c8b33836108cf00",
        "windows_arm64" to "ec86643f9a79754a1000ed03fab65387861d071ed2f62e10fe01395d65ca30d3",
        "linux_x86_64" to "f567e52961d8a85595a55f1d716d075e337d6cb9fe901ba1e1ec60d33bd32112",
        "linux_arm64" to "f29cdb74b592bdeb426bb93f121bcbfc5f1d64b8e4ebff9d924ba7b8260b262d",
        "darwin_x86_64" to "6150f9673670d48ccb4a94b7d9e1d92a8932a76349bb483d36816013ba9f26c6",
        "darwin_arm64" to "24ac3750fcba2532c02c48411eaf76aaf29058f0daf851ee4d449031b621e9fa"
    ),
    "2024.3.2" to mapOf(
        "windows_x86_64" to "23d5e0afdebdcd0c9a28117c0d5b7c5a33300876637fa96eef1b1668d0a71f49",
        "windows_arm64" to "5cb634fad9b88377d7d53593f89ea3b8aa7d748b9d34108c0d5b8c4a460245d0",
        "linux_x86_64" to "d5025e1ef5cd61c7d7fb99951f6f9256f07876a388945a5dafa7895669ef4e9e",
        "linux_arm64" to "f1f4a85693ba701fc13d3f70e94679b5be7d8a07d4087ceeb1195cf24895e77c",
        "darwin_x86_64" to "17afbd22c8538b01b45a1aee3e1697ae5fd835d92ed1c916085e092f01cdd24f",
        "darwin_arm64" to "70c4dfd3d9b63f45af3a1538bb1e52560ef55c8dbfe61e00494a3666abf1ad5a"
    ),
    "2024.3.3" to mapOf(
        "windows_x86_64" to "30d5221a72ed75a974a6d163dec83c1ce9ab8b68fe9ca64152c8c695e30d2841",
        "windows_arm64" to "d039171c502712a0b5e490daee18dde7ec0fd26c7cb70fe5d0128072986f1cda",
        "linux_x86_64" to "c77660f98b78f0253bc5b9050ee4841aa895ba9e045c522525edb94fcb1e9075",
        "linux_arm64" to "62a74256ad6e7a7075976e83dbcc6be150176ffd710c8efbe0c62491507983f3",
        "darwin_x86_64" to "c7d80eaaa6ccf7cd351a46b5cd4fd0523cbd0d02bda1e1200e23bd3b5300f3f0",
        "darwin_arm64" to "124f3ffc43d72eea071338ff7c4589f4656a541d0461cb0073146c4d50a30588"
    ),
    "2024.3.4" to mapOf(
        "windows_x86_64" to "98e2ceaa8899b41350cc2f43cc4a267a08955781a5edef6e49f64ddc2d8f2daf",
        "windows_arm64" to "3ed4f077c7eab5ad125a780e4fbc7bf5f07cc4ba38e73bca7e3ca571fbee865f",
        "linux_x86_64" to "bc81fe9d454ef5e26bc8171082b77c729823409f55d328c18371bee1397ec2cd",
        "linux_arm64" to "61faf41a8d8863d8bc5bdd7d8c8d93400b17617124ded616772d3fe751ffa103",
        "darwin_x86_64" to "537d251621a63b96a196191004357d85cbc5c8bfff1ec2327bb2f2da141900f5",
        "darwin_arm64" to "0830c6c4cba3a2cee6884cbbc10fd43d5d68fb4c3ecd3fd34faa181961726204"
    ),
    "2024.3.5" to mapOf(
        "windows_x86_64" to "36ebe2e9f9a7f917f75bad869fd89c1dc038bed3121670e660fdb4393353186d",
        "windows_arm64" to "6cd9544064ea71f860548a5fd5491727dfd5aff4d9839c6cf3a57fe5edb77a81",
        "linux_x86_64" to "fc0872418f14d295acb96116acb4652f5f5f0e22c63360ef4aa3b4c3bfe117fb",
        "linux_arm64" to "d771176c7b9bef12e16d874f12b0ec5b96c5dd6494858dfcd8661063dc101b93",
        "darwin_x86_64" to "ac0f967b6b4ad71e74554bcd34ba3c51e45d73ba546867f245878136c5cde2d2",
        "darwin_arm64" to "4fdb34ddca48c892ab6d2938c1279538c80cf5657c35f43e055c61efdda8d39d"
    )
)