version: "1.0"
linter: jetbrains/qodana-jvm:latest
projectJDK: 11
profile:
  name: qodana.recommended.full
exclude:
  - name: All
    paths:
      - node_modules/
      - common/node_modules/
      - scan/node_modules/
      - vsts/node_modules/
      - common/lib
      - scan/lib
      - scan/dist
      - scan/__tests__
      - vsts/QodanaScan
      - build.gradle.kts
      - settings.gradle.kts
      - common
      - scan
      - vsts
include:
  - name: Eslint
  - name: GrazieInspection
  - name: IdentifierGrammar
  - name: LanguageDetectionInspection
  - name: CheckDependencyLicenses
licenseRules:
  - keys:
      - "Apache-2.0"
    allowed:
      - "0BSD"
      - "FPL"
